site.url# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Thinny
tagline:          'blog'
description:      'My personal blog.'
url:              http://#
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Ian Brunelli
  url:            https://#

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         twitter
    url:          https://#
    desc:         Follow me on twitter

  - icon:         github
    url:          https://#
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://#
    desc:         Add me on google+

  - icon:         feed
    url:          http://#
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Vezde
  url:            http://#
  type_title:     Some rights reserved
  type_url:       http://#

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
